# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Luis Santos custom theme"
license = "MIT"
description = "Ported theme of HTML5 UP, future imperfect, with some extra goodies"
homepage = "https://github.com/jpescador/hugo-future-imperfect"
tags = ["blog", "responsive", "font awesome", "highlight.js"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Luis Santos"
